# Generated by Django 4.2.1 on 2023-08-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromwhere', models.CharField(choices=[('Deneme1', 'Deneme1'), ('Deneme2', 'Deneme2'), ('Deneme3', 'Deneme3')], default='Deneme1', max_length=7)),
                ('towhere', models.CharField(choices=[('Deneme1', 'Deneme1'), ('Deneme2', 'Deneme2'), ('Deneme3', 'Deneme3')], default='Deneme2', max_length=7)),
                ('numberpeople', models.CharField(choices=[('Yetişkin', (('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'))), ('Çocuk', (('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')))], default='1', max_length=1)),
            ],
        ),
    ]
