# Generated by Django 4.2.1 on 2023-08-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_alter_transfer_adultnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='fromwhere_de',
            field=models.CharField(choices=[('Deneme1', 'Deneme1'), ('Deneme2', 'Deneme2'), ('Deneme3', 'Deneme3')], default='-----', max_length=7, null=True, verbose_name='Nereden'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='fromwhere_en',
            field=models.CharField(choices=[('Deneme1', 'Deneme1'), ('Deneme2', 'Deneme2'), ('Deneme3', 'Deneme3')], default='-----', max_length=7, null=True, verbose_name='Nereden'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='fromwhere_tr',
            field=models.CharField(choices=[('Deneme1', 'Deneme1'), ('Deneme2', 'Deneme2'), ('Deneme3', 'Deneme3')], default='-----', max_length=7, null=True, verbose_name='Nereden'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='towhere_de',
            field=models.CharField(choices=[('Deneme1', 'Deneme1'), ('Deneme2', 'Deneme2'), ('Deneme3', 'Deneme3')], default='-----', max_length=7, null=True, verbose_name='Nereye'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='towhere_en',
            field=models.CharField(choices=[('Deneme1', 'Deneme1'), ('Deneme2', 'Deneme2'), ('Deneme3', 'Deneme3')], default='-----', max_length=7, null=True, verbose_name='Nereye'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='towhere_tr',
            field=models.CharField(choices=[('Deneme1', 'Deneme1'), ('Deneme2', 'Deneme2'), ('Deneme3', 'Deneme3')], default='-----', max_length=7, null=True, verbose_name='Nereye'),
        ),
    ]
