# Generated by Django 4.2.1 on 2023-08-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_fromwhere_towhere_car_alter_transfer_fromwhere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='capasity_de',
            field=models.CharField(choices=[('1-3 Kişi', '1-3 Kişi'), ('1-6 Kişi', '1-6 Kişi'), ('1-13 Kişi', '1-13 Kişi')], max_length=10, null=True, verbose_name='Kapasite'),
        ),
        migrations.AddField(
            model_name='car',
            name='capasity_en',
            field=models.CharField(choices=[('1-3 Kişi', '1-3 Kişi'), ('1-6 Kişi', '1-6 Kişi'), ('1-13 Kişi', '1-13 Kişi')], max_length=10, null=True, verbose_name='Kapasite'),
        ),
        migrations.AddField(
            model_name='car',
            name='capasity_tr',
            field=models.CharField(choices=[('1-3 Kişi', '1-3 Kişi'), ('1-6 Kişi', '1-6 Kişi'), ('1-13 Kişi', '1-13 Kişi')], max_length=10, null=True, verbose_name='Kapasite'),
        ),
        migrations.AddField(
            model_name='car',
            name='currency_de',
            field=models.CharField(blank=True, default='TRY', max_length=3, null=True, verbose_name='Birim'),
        ),
        migrations.AddField(
            model_name='car',
            name='currency_en',
            field=models.CharField(blank=True, default='TRY', max_length=3, null=True, verbose_name='Birim'),
        ),
        migrations.AddField(
            model_name='car',
            name='currency_tr',
            field=models.CharField(blank=True, default='TRY', max_length=3, null=True, verbose_name='Birim'),
        ),
        migrations.AddField(
            model_name='car',
            name='max_people_de',
            field=models.IntegerField(null=True, verbose_name='MaxPeople'),
        ),
        migrations.AddField(
            model_name='car',
            name='max_people_en',
            field=models.IntegerField(null=True, verbose_name='MaxPeople'),
        ),
        migrations.AddField(
            model_name='car',
            name='max_people_tr',
            field=models.IntegerField(null=True, verbose_name='MaxPeople'),
        ),
        migrations.AddField(
            model_name='car',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='car',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='car',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='car',
            name='price_de',
            field=models.IntegerField(null=True, verbose_name='Ücret'),
        ),
        migrations.AddField(
            model_name='car',
            name='price_en',
            field=models.IntegerField(null=True, verbose_name='Ücret'),
        ),
        migrations.AddField(
            model_name='car',
            name='price_tr',
            field=models.IntegerField(null=True, verbose_name='Ücret'),
        ),
    ]
