# Generated by Django 4.2.1 on 2023-08-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_car_capasity_de_car_capasity_en_car_capasity_tr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='capasity',
            field=models.CharField(max_length=20, verbose_name='Kapasite'),
        ),
        migrations.AlterField(
            model_name='car',
            name='capasity_de',
            field=models.CharField(max_length=20, null=True, verbose_name='Kapasite'),
        ),
        migrations.AlterField(
            model_name='car',
            name='capasity_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Kapasite'),
        ),
        migrations.AlterField(
            model_name='car',
            name='capasity_tr',
            field=models.CharField(max_length=20, null=True, verbose_name='Kapasite'),
        ),
    ]
