# Generated by Django 4.2.1 on 2023-08-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0008_alter_car_capasity_alter_car_capasity_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towhere',
            name='fromwhere',
        ),
    ]
