# Generated by Django 4.2.1 on 2023-08-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0009_remove_towhere_fromwhere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='capasity_de',
        ),
        migrations.RemoveField(
            model_name='car',
            name='capasity_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='capasity_tr',
        ),
        migrations.RemoveField(
            model_name='car',
            name='currency_de',
        ),
        migrations.RemoveField(
            model_name='car',
            name='currency_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='currency_tr',
        ),
        migrations.RemoveField(
            model_name='car',
            name='max_people_de',
        ),
        migrations.RemoveField(
            model_name='car',
            name='max_people_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='max_people_tr',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name_tr',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_de',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_tr',
        ),
    ]
