# Generated by Django 4.2.1 on 2023-08-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0012_remove_car_capasity_de_remove_car_capasity_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='fromwhere_de',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='fromwhere_en',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='fromwhere_tr',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='towhere_de',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='towhere_en',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='towhere_tr',
        ),
        migrations.AddField(
            model_name='fromwhere',
            name='name_de',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='fromwhere',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='fromwhere',
            name='name_tr',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='towhere',
            name='name_de',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='towhere',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='towhere',
            name='name_tr',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
    ]
