# Generated by Django 4.2.1 on 2023-08-18 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0013_remove_transfer_fromwhere_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='capasity_de',
            field=models.CharField(max_length=20, null=True, verbose_name='Kapasite'),
        ),
        migrations.AddField(
            model_name='car',
            name='capasity_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Kapasite'),
        ),
        migrations.AddField(
            model_name='car',
            name='capasity_tr',
            field=models.CharField(max_length=20, null=True, verbose_name='Kapasite'),
        ),
        migrations.AddField(
            model_name='car',
            name='currency_de',
            field=models.CharField(blank=True, default='TRY', max_length=3, null=True, verbose_name='Birim'),
        ),
        migrations.AddField(
            model_name='car',
            name='currency_en',
            field=models.CharField(blank=True, default='TRY', max_length=3, null=True, verbose_name='Birim'),
        ),
        migrations.AddField(
            model_name='car',
            name='currency_tr',
            field=models.CharField(blank=True, default='TRY', max_length=3, null=True, verbose_name='Birim'),
        ),
        migrations.AddField(
            model_name='car',
            name='fromwhere_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.fromwhere', verbose_name='Nereden'),
        ),
        migrations.AddField(
            model_name='car',
            name='fromwhere_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.fromwhere', verbose_name='Nereden'),
        ),
        migrations.AddField(
            model_name='car',
            name='fromwhere_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.fromwhere', verbose_name='Nereden'),
        ),
        migrations.AddField(
            model_name='car',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='car',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='car',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='car',
            name='price_de',
            field=models.IntegerField(null=True, verbose_name='Ücret'),
        ),
        migrations.AddField(
            model_name='car',
            name='price_en',
            field=models.IntegerField(null=True, verbose_name='Ücret'),
        ),
        migrations.AddField(
            model_name='car',
            name='price_tr',
            field=models.IntegerField(null=True, verbose_name='Ücret'),
        ),
        migrations.AddField(
            model_name='car',
            name='towhere_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.towhere', verbose_name='Nereye'),
        ),
        migrations.AddField(
            model_name='car',
            name='towhere_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.towhere', verbose_name='Nereye'),
        ),
        migrations.AddField(
            model_name='car',
            name='towhere_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.towhere', verbose_name='Nereye'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='fromwhere_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.fromwhere', verbose_name='Nereden'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='fromwhere_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.fromwhere', verbose_name='Nereden'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='fromwhere_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.fromwhere', verbose_name='Nereden'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='towhere_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.towhere', verbose_name='Nereye'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='towhere_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.towhere', verbose_name='Nereye'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='towhere_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.towhere', verbose_name='Nereye'),
        ),
    ]
