# Generated by Django 4.2.1 on 2023-08-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0014_car_capasity_de_car_capasity_en_car_capasity_tr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='adultnumber',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], verbose_name='Yetişkin'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='childrennumber',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='Çocuk'),
        ),
    ]
