# Generated by Django 4.2.1 on 2023-08-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0015_alter_transfer_adultnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='adultnumber',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, verbose_name='Yetişkin'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='childrennumber',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, verbose_name='Çocuk'),
        ),
    ]
