# Generated by Django 4.2.1 on 2023-08-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0017_alter_transfer_adultnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='currency',
            field=models.CharField(blank=True, default='₺', max_length=3, verbose_name='Birim'),
        ),
        migrations.AlterField(
            model_name='car',
            name='currency_de',
            field=models.CharField(blank=True, default='₺', max_length=3, null=True, verbose_name='Birim'),
        ),
        migrations.AlterField(
            model_name='car',
            name='currency_en',
            field=models.CharField(blank=True, default='₺', max_length=3, null=True, verbose_name='Birim'),
        ),
        migrations.AlterField(
            model_name='car',
            name='currency_tr',
            field=models.CharField(blank=True, default='₺', max_length=3, null=True, verbose_name='Birim'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='adultnumber',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', help_text='Lütfen listeden bir öge seçin.', max_length=2, verbose_name='Yetişkin'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='childrennumber',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', help_text='Lütfen listeden bir öge seçin.', max_length=2, verbose_name='Çocuk'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='fromwhere',
            field=models.ForeignKey(help_text='Lütfen listeden bir öge seçin.', on_delete=django.db.models.deletion.CASCADE, to='transfer.fromwhere', verbose_name='Nereden'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='fromwhere_de',
            field=models.ForeignKey(help_text='Lütfen listeden bir öge seçin.', null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.fromwhere', verbose_name='Nereden'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='fromwhere_en',
            field=models.ForeignKey(help_text='Lütfen listeden bir öge seçin.', null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.fromwhere', verbose_name='Nereden'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='fromwhere_tr',
            field=models.ForeignKey(help_text='Lütfen listeden bir öge seçin.', null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.fromwhere', verbose_name='Nereden'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='towhere',
            field=models.ForeignKey(help_text='Lütfen listeden bir öge seçin.', on_delete=django.db.models.deletion.CASCADE, to='transfer.towhere', verbose_name='Nereye'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='towhere_de',
            field=models.ForeignKey(help_text='Lütfen listeden bir öge seçin.', null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.towhere', verbose_name='Nereye'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='towhere_en',
            field=models.ForeignKey(help_text='Lütfen listeden bir öge seçin.', null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.towhere', verbose_name='Nereye'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='towhere_tr',
            field=models.ForeignKey(help_text='Lütfen listeden bir öge seçin.', null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.towhere', verbose_name='Nereye'),
        ),
    ]
