# Generated by Django 4.2.1 on 2023-08-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0019_remove_car_currency_de_remove_car_currency_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ad')),
                ('extra_image', models.FileField(upload_to='', verbose_name='Resim')),
                ('price', models.IntegerField(verbose_name='Ücret')),
            ],
        ),
    ]
