# Generated by Django 4.2.1 on 2023-08-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0020_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='name_de',
            field=models.CharField(max_length=20, null=True, verbose_name='Ad'),
        ),
        migrations.AddField(
            model_name='extras',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Ad'),
        ),
        migrations.AddField(
            model_name='extras',
            name='name_tr',
            field=models.CharField(max_length=20, null=True, verbose_name='Ad'),
        ),
    ]
