# Generated by Django 4.2.1 on 2023-08-29 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0021_extras_name_de_extras_name_en_extras_name_tr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=55, verbose_name='name')),
                ('symbol', models.CharField(blank=True, max_length=4, verbose_name='symbol')),
                ('factor', models.DecimalField(decimal_places=10, default=1.0, max_digits=30, verbose_name='factor')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 29), verbose_name='Transfer Tarihi'),
        ),
    ]
