# Generated by Django 4.2.1 on 2023-08-31 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0022_currency_alter_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='bill_mail',
            field=models.CharField(blank=True, choices=[('Biriysel Fatura', 'Bireysel Fatura'), ('Kurumsal Fatura', 'Kurumsal Fatura')], default=' ', max_length=100, null=True, verbose_name='Mail Durumu'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mail_context',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='Fatura Detay'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 31), verbose_name='Transfer Tarihi'),
        ),
    ]
