# Generated by Django 4.2.1 on 2023-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0026_reservation_total_amount_alter_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(default='Araçta Nakit', max_length=20, verbose_name='Ödeme Yöntemi'),
        ),
    ]
