# Generated by Django 4.2.1 on 2023-09-10 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0027_reservation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 10), verbose_name='Transfer Tarihi'),
        ),
    ]
