# Generated by Django 4.2.1 on 2023-09-11 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0028_alter_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='mail_choices',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True, verbose_name='Fatura Türü'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 11), verbose_name='Transfer Tarihi'),
        ),
    ]
