# Generated by Django 4.2.1 on 2023-09-12 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0029_reservation_mail_choices_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 12), verbose_name='Transfer Tarihi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='mail_choices',
            field=models.CharField(blank=True, default='İstek Oluşturulmamış', max_length=10, null=True, verbose_name='Fatura Türü'),
        ),
    ]
