# Generated by Django 4.2.1 on 2023-09-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0030_alter_reservation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='another_traveller',
            field=models.CharField(default=' ', max_length=100, verbose_name='Yolcular'),
        ),
    ]
