# Generated by Django 4.2.1 on 2023-09-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0033_alter_reservation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='mail_context',
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='İşlemde', max_length=15, verbose_name='Durum'),
        ),
    ]
