# Generated by Django 4.2.1 on 2023-10-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0037_alter_blog_article_image_alter_reservation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='image',
            field=models.FileField(default='', upload_to='', verbose_name='Resim'),
        ),
    ]
