# Generated by Django 4.2.1 on 2023-11-04 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0039_reservation_passport_no_alter_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_of_return',
            field=models.DateField(default=datetime.date(2023, 11, 4), verbose_name='Dönüş Tarihi'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_of_return',
            field=models.TimeField(default='13:59', verbose_name='Dönüş Saati'),
        ),
    ]
