# Generated by Django 4.2.1 on 2023-11-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0040_reservation_date_of_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='mail_context',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='Fatura Detay'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_of_return',
            field=models.TimeField(default='14:28', verbose_name='Dönüş Saati'),
        ),
    ]
