# Generated by Django 4.2.1 on 2023-11-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0041_reservation_mail_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='flightnumber_of_return',
            field=models.CharField(default='', max_length=20, verbose_name='Dönüş Uçuş Numarası'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_of_return',
            field=models.TimeField(default='15:40', verbose_name='Dönüş Saati'),
        ),
    ]
