# Generated by Django 4.2.1 on 2023-11-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0043_alter_reservation_flightnumber_of_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_of_return',
            field=models.TimeField(default='16:02', verbose_name='Dönüş Saati'),
        ),
        migrations.DeleteModel(
            name='Popular',
        ),
    ]
