# Generated by Django 4.2.1 on 2023-11-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0044_alter_reservation_time_of_return_delete_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageArticleOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('title_tr', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_de', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('content_tr', models.TextField(null=True, verbose_name='İçerik')),
                ('content_en', models.TextField(null=True, verbose_name='İçerik')),
                ('content_de', models.TextField(null=True, verbose_name='İçerik')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_of_return',
            field=models.TimeField(default='16:38', verbose_name='Dönüş Saati'),
        ),
    ]
