# Generated by Django 4.2.1 on 2023-11-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0045_homepagearticleone_alter_reservation_time_of_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagearticleone',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_of_return',
            field=models.TimeField(default='16:39', verbose_name='Dönüş Saati'),
        ),
    ]
