# Generated by Django 4.2.1 on 2023-11-05 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0046_homepagearticleone_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageArticleTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('title_tr', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('title_de', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('content_tr', models.TextField(null=True, verbose_name='İçerik')),
                ('content_en', models.TextField(null=True, verbose_name='İçerik')),
                ('content_de', models.TextField(null=True, verbose_name='İçerik')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2023, 11, 5), verbose_name='Transfer Tarihi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_of_return',
            field=models.DateField(default=datetime.date(2023, 11, 5), verbose_name='Dönüş Tarihi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_of_return',
            field=models.TimeField(default='13:16', verbose_name='Dönüş Saati'),
        ),
    ]
