# Generated by Django 4.2.1 on 2023-12-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0050_blog_content_ru_blog_title_ru_car_capasity_ru_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransferTypes',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_of_return',
            field=models.TimeField(default='15:30', verbose_name='Dönüş Saati'),
        ),
    ]
