# Generated by Django 4.2.1 on 2023-12-29 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0051_delete_transfertypes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='max_people',
            field=models.IntegerField(verbose_name='En Çok Kişi Sayısı'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 29), verbose_name='Transfer Tarihi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_of_return',
            field=models.DateField(default=datetime.date(2023, 12, 29), verbose_name='Dönüş Tarihi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_of_return',
            field=models.TimeField(default='17:31', verbose_name='Dönüş Saati'),
        ),
    ]
